<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\backend\CarExpenseCalculator.Infrastructure\CarExpenseCalculator.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\backend\CarExpenseCalculator.Extraction.Contracts\CarExpenseCalculator.Extraction.Contracts.csproj" />
  </ItemGroup>
</Project>
