/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/listing-analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ListingAnalysisRequest"];
                    "application/*+json": components["schemas"]["ListingAnalysisRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListingAnalysisResponse"];
                        "application/json": components["schemas"]["ListingAnalysisResponse"];
                        "text/json": components["schemas"]["ListingAnalysisResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ListingAnalysisProblemDetails"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ListingAnalysisProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manual-calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ManualCalculationRequest"];
                    "application/*+json": components["schemas"]["ManualCalculationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ManualCalculationResult"];
                        "application/json": components["schemas"]["ManualCalculationResult"];
                        "text/json": components["schemas"]["ManualCalculationResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-cost-scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedCostScenarioSummaryResponse"][];
                        "application/json": components["schemas"]["SavedCostScenarioSummaryResponse"][];
                        "text/json": components["schemas"]["SavedCostScenarioSummaryResponse"][];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSavedCostScenarioRequest"];
                    "application/*+json": components["schemas"]["CreateSavedCostScenarioRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedCostScenarioResponse"];
                        "application/json": components["schemas"]["SavedCostScenarioResponse"];
                        "text/json": components["schemas"]["SavedCostScenarioResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-cost-scenarios/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedCostScenarioResponse"];
                        "application/json": components["schemas"]["SavedCostScenarioResponse"];
                        "text/json": components["schemas"]["SavedCostScenarioResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReplaceSavedCostScenarioRequest"];
                    "application/*+json": components["schemas"]["ReplaceSavedCostScenarioRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedCostScenarioResponse"];
                        "application/json": components["schemas"]["SavedCostScenarioResponse"];
                        "text/json": components["schemas"]["SavedCostScenarioResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    expectedRevision: number;
                };
                header?: never;
                path: {
                    vehicleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-cost-scenarios/by-registration/{registrationNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    registrationNumber: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedCostScenarioResponse"];
                        "application/json": components["schemas"]["SavedCostScenarioResponse"];
                        "text/json": components["schemas"]["SavedCostScenarioResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedCostScenarioProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedListingSummaryResponse"][];
                        "application/json": components["schemas"]["SavedListingSummaryResponse"][];
                        "text/json": components["schemas"]["SavedListingSummaryResponse"][];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSavedListingRequest"];
                    "application/*+json": components["schemas"]["CreateSavedListingRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedListingResponse"];
                        "application/json": components["schemas"]["SavedListingResponse"];
                        "text/json": components["schemas"]["SavedListingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-listings/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedListingResponse"];
                        "application/json": components["schemas"]["SavedListingResponse"];
                        "text/json": components["schemas"]["SavedListingResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    vehicleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReplaceSavedListingRequest"];
                    "application/*+json": components["schemas"]["ReplaceSavedListingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedListingResponse"];
                        "application/json": components["schemas"]["SavedListingResponse"];
                        "text/json": components["schemas"]["SavedListingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query: {
                    expectedRevision: number;
                };
                header?: never;
                path: {
                    vehicleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-listings/by-registration/{registrationNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    registrationNumber: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedListingResponse"];
                        "application/json": components["schemas"]["SavedListingResponse"];
                        "text/json": components["schemas"]["SavedListingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["SavedListingProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemStatusResponse"];
                        "application/json": components["schemas"]["SystemStatusResponse"];
                        "text/json": components["schemas"]["SystemStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BodyType: "sedan" | "hatchback" | "wagon" | "suv" | "coupe" | "convertible" | "minivan" | "pickup" | "van" | "other";
        CalculationCompleteness: {
            isComplete: boolean;
            isCashFlowComplete: boolean;
            isNetOwnershipCostAvailable: boolean;
            missingCategories: components["schemas"]["MissingCategory"][];
        };
        CashFlowResult: {
            /** Format: double */
            acquisitionCashPaidSek: number;
            /** Format: double */
            loanPaymentsDuringPeriodSek: number;
            /** Format: double */
            energyCostSek: number;
            /** Format: double */
            vehicleTaxSek: null | number;
            /** Format: double */
            insuranceSek: null | number;
            /** Format: double */
            maintenanceAndRepairsSek: null | number;
            /** Format: double */
            otherRecurringCostSek: number;
            /** Format: double */
            otherOneTimeCostSek: number;
            /** Format: double */
            knownOperatingCostSek: number;
            /** Format: double */
            knownTotalSek: number;
            /** Format: double */
            averagePerMonthSek: number;
            /** Format: double */
            averagePerYearSek: number;
            isComplete: boolean;
        };
        CreateSavedCostScenarioRequest: {
            registrationNumber: string;
            scenario: components["schemas"]["ManualCalculationRequest"];
        };
        CreateSavedListingRequest: {
            registrationNumber: string;
            listing: components["schemas"]["ReviewedListingInput"];
        };
        /** @enum {unknown} */
        Drivetrain: "frontWheelDrive" | "rearWheelDrive" | "allWheelDrive";
        EnergyBreakdownResult: {
            sources: components["schemas"]["EnergySourceResult"][];
            /** Format: double */
            totalCostSek: number;
        };
        EnergyConsumptionInput: {
            label: string;
            unit: components["schemas"]["EnergyUnit"];
            /** Format: double */
            consumptionPer100Kilometres: number;
        };
        EnergyConsumptionResponse: {
            label: string;
            unit: components["schemas"]["EnergyUnit"];
            /** Format: double */
            consumptionPer100Kilometres: number;
        };
        EnergySourceInput: {
            label: string;
            unit: components["schemas"]["EnergyUnit"];
            /** Format: double */
            consumptionPer100Kilometres: number;
            /** Format: double */
            pricePerUnitSek: number;
            /** Format: double */
            distanceSharePercent: number;
        };
        EnergySourceResult: {
            label: string;
            unit: components["schemas"]["EnergyUnit"];
            /** Format: double */
            distanceSharePercent: number;
            /** Format: double */
            allocatedDistanceKilometres: number;
            /** Format: double */
            consumptionPer100Kilometres: number;
            /** Format: double */
            consumedQuantity: number;
            /** Format: double */
            pricePerUnitSek: number;
            /** Format: double */
            costSek: number;
        };
        /** @enum {unknown} */
        EnergyUnit: "litre" | "kilowattHour" | "kilogram";
        /** @enum {unknown} */
        ExtractionMethod: "ai" | "manual";
        FeatureStatusResponse: {
            ruleBasedSearch: boolean;
            urlAnalysis: boolean;
            manualCalculator: boolean;
            aiReview: boolean;
        };
        /** @enum {unknown} */
        FieldOrigin: "listing" | "user" | "registry";
        FieldProvenanceInput: {
            origin: components["schemas"]["FieldOrigin"];
            extractionMethod: components["schemas"]["ExtractionMethod"];
            verification: components["schemas"]["VerificationStatus"];
            sourceUrl: string;
        };
        FieldProvenanceResponse: {
            origin: components["schemas"]["FieldOrigin"];
            extractionMethod: components["schemas"]["ExtractionMethod"];
            verification: components["schemas"]["VerificationStatus"];
            sourceUrl: string;
        };
        FinancingInput: {
            /** Format: double */
            downPaymentSek: number;
            /** Format: double */
            annualNominalInterestRatePercent: number;
            /** Format: int32 */
            termMonths: number;
        };
        FinancingResult: {
            /** Format: double */
            downPaymentSek: number;
            /** Format: double */
            principalSek: number;
            /** Format: double */
            annualNominalInterestRatePercent: number;
            /** Format: int32 */
            termMonths: number;
            /** Format: double */
            monthlyPaymentSek: number;
            /** Format: int32 */
            paymentsMade: number;
            /** Format: double */
            loanPaymentsDuringPeriodSek: number;
            /** Format: double */
            principalRepaidSek: number;
            /** Format: double */
            interestPaidSek: number;
            /** Format: double */
            remainingPrincipalSek: number;
        };
        /** @enum {unknown} */
        FuelType: "petrol" | "diesel" | "electricity" | "ethanol" | "biogas" | "naturalGas" | "liquefiedPetroleumGas" | "hydrogen" | "other";
        IntegrationStatusResponse: {
            codexListingExtractionConfigured: boolean;
        };
        ListingAnalysisProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            code: string;
        };
        ListingAnalysisRequest: {
            url: string;
        };
        ListingAnalysisResponse: {
            submittedUrl: string;
            normalizedUrl: string;
            status: components["schemas"]["ListingAnalysisStatus"];
            /** Format: date-time */
            analyzedAtUtc: string;
            requestedModel: string;
            /** Format: int32 */
            promptVersion: number;
            /** Format: int32 */
            schemaVersion: number;
            sources: components["schemas"]["ListingAnalysisSourceResponse"][];
            listing: components["schemas"]["ListingDraftResponse"];
            missingFields: components["schemas"]["ListingFieldCode"][];
        };
        ListingAnalysisSourceResponse: {
            url: string;
            matchesSubmittedUrl: boolean;
        };
        /** @enum {unknown} */
        ListingAnalysisStatus: "complete" | "partial" | "unavailable";
        ListingDraftInput: {
            registrationNumber: null | components["schemas"]["SourcedValueInputOfstring"];
            make: null | components["schemas"]["SourcedValueInputOfstring"];
            model: null | components["schemas"]["SourcedValueInputOfstring"];
            variant: null | components["schemas"]["SourcedValueInputOfstring"];
            modelYear: null | components["schemas"]["SourcedValueInputOfint"];
            vin: null | components["schemas"]["SourcedValueInputOfstring"];
            vehicleLabel: null | components["schemas"]["SourcedValueInputOfstring"];
            priceSek: null | components["schemas"]["SourcedValueInputOfdecimal"];
            odometerKilometres: null | components["schemas"]["SourcedValueInputOfdecimal"];
            sellerType: null | components["schemas"]["SourcedValueInputOfSellerType"];
            locality: null | components["schemas"]["SourcedValueInputOfstring"];
            county: null | components["schemas"]["SourcedValueInputOfstring"];
            publishedDate: null | components["schemas"]["SourcedValueInputOfDateOnly"];
            updatedDate: null | components["schemas"]["SourcedValueInputOfDateOnly"];
            imageCount: null | components["schemas"]["SourcedValueInputOfint"];
            fuelTypes: null | components["schemas"]["SourcedCollectionInputOfFuelType"];
            transmission: null | components["schemas"]["SourcedValueInputOfTransmission"];
            drivetrain: null | components["schemas"]["SourcedValueInputOfDrivetrain"];
            bodyType: null | components["schemas"]["SourcedValueInputOfBodyType"];
            colour: null | components["schemas"]["SourcedValueInputOfstring"];
            horsepower: null | components["schemas"]["SourcedValueInputOfint"];
            engineDisplacementCubicCentimetres: null | components["schemas"]["SourcedValueInputOfdecimal"];
            energyConsumptions: null | components["schemas"]["SourcedCollectionInputOfEnergyConsumptionInput"];
            annualVehicleTaxSek: null | components["schemas"]["SourcedValueInputOfdecimal"];
            ownerCount: null | components["schemas"]["SourcedValueInputOfint"];
            firstRegistrationDate: null | components["schemas"]["SourcedValueInputOfDateOnly"];
            lastInspectionDate: null | components["schemas"]["SourcedValueInputOfDateOnly"];
            nextInspectionDate: null | components["schemas"]["SourcedValueInputOfDateOnly"];
            towBar: null | components["schemas"]["SourcedValueInputOfboolean"];
            equipment: null | components["schemas"]["SourcedCollectionInputOfstring"];
            sellerClaims: null | components["schemas"]["SourcedCollectionInputOfstring"];
            conditionNotes: null | components["schemas"]["SourcedCollectionInputOfstring"];
        };
        ListingDraftResponse: {
            registrationNumber: null | components["schemas"]["SourcedValueResponseOfstring"];
            make: null | components["schemas"]["SourcedValueResponseOfstring"];
            model: null | components["schemas"]["SourcedValueResponseOfstring"];
            variant: null | components["schemas"]["SourcedValueResponseOfstring"];
            modelYear: null | components["schemas"]["SourcedValueResponseOfint"];
            vin: null | components["schemas"]["SourcedValueResponseOfstring"];
            vehicleLabel: null | components["schemas"]["SourcedValueResponseOfstring"];
            priceSek: null | components["schemas"]["SourcedValueResponseOfdecimal"];
            odometerKilometres: null | components["schemas"]["SourcedValueResponseOfdecimal"];
            sellerType: null | components["schemas"]["SourcedValueResponseOfSellerType"];
            locality: null | components["schemas"]["SourcedValueResponseOfstring"];
            county: null | components["schemas"]["SourcedValueResponseOfstring"];
            publishedDate: null | components["schemas"]["SourcedValueResponseOfDateOnly"];
            updatedDate: null | components["schemas"]["SourcedValueResponseOfDateOnly"];
            imageCount: null | components["schemas"]["SourcedValueResponseOfint"];
            fuelTypes: null | components["schemas"]["SourcedCollectionResponseOfFuelType"];
            transmission: null | components["schemas"]["SourcedValueResponseOfTransmission"];
            drivetrain: null | components["schemas"]["SourcedValueResponseOfDrivetrain"];
            bodyType: null | components["schemas"]["SourcedValueResponseOfBodyType"];
            colour: null | components["schemas"]["SourcedValueResponseOfstring"];
            horsepower: null | components["schemas"]["SourcedValueResponseOfint"];
            engineDisplacementCubicCentimetres: null | components["schemas"]["SourcedValueResponseOfdecimal"];
            energyConsumptions: null | components["schemas"]["SourcedCollectionResponseOfEnergyConsumptionResponse"];
            annualVehicleTaxSek: null | components["schemas"]["SourcedValueResponseOfdecimal"];
            ownerCount: null | components["schemas"]["SourcedValueResponseOfint"];
            firstRegistrationDate: null | components["schemas"]["SourcedValueResponseOfDateOnly"];
            lastInspectionDate: null | components["schemas"]["SourcedValueResponseOfDateOnly"];
            nextInspectionDate: null | components["schemas"]["SourcedValueResponseOfDateOnly"];
            towBar: null | components["schemas"]["SourcedValueResponseOfboolean"];
            equipment: null | components["schemas"]["SourcedCollectionResponseOfstring"];
            sellerClaims: null | components["schemas"]["SourcedCollectionResponseOfstring"];
            conditionNotes: null | components["schemas"]["SourcedCollectionResponseOfstring"];
        };
        /** @enum {unknown} */
        ListingFieldCode: "registrationNumber" | "make" | "model" | "variant" | "modelYear" | "vin" | "priceSek" | "odometerKilometres" | "sellerType" | "locality" | "county" | "publishedDate" | "updatedDate" | "imageCount" | "fuelTypes" | "transmission" | "drivetrain" | "bodyType" | "colour" | "horsepower" | "engineDisplacementCubicCentimetres" | "energyConsumptions" | "annualVehicleTaxSek" | "ownerCount" | "firstRegistrationDate" | "lastInspectionDate" | "nextInspectionDate" | "towBar" | "equipment" | "sellerClaims" | "conditionNotes";
        ManualCalculationRequest: {
            vehicleLabel?: null | string;
            /** Format: int32 */
            calculationPeriodMonths: number;
            /** Format: double */
            purchasePriceSek: number;
            /** Format: double */
            expectedResidualValueSek?: null | number;
            /** Format: double */
            annualDistanceKilometres: number;
            financing?: null | components["schemas"]["FinancingInput"];
            energySources: components["schemas"]["EnergySourceInput"][];
            vehicleTax: null | components["schemas"]["RecurringCostInput"];
            insurance: null | components["schemas"]["RecurringCostInput"];
            maintenanceAndRepairs: null | components["schemas"]["RecurringCostInput"];
            otherRecurringCosts: components["schemas"]["NamedRecurringCostInput"][];
            otherOneTimeCosts: components["schemas"]["OneTimeCostInput"][];
        };
        ManualCalculationResult: {
            currency: string;
            /** Format: int32 */
            calculationPeriodMonths: number;
            /** Format: double */
            totalDistanceKilometres: number;
            completeness: components["schemas"]["CalculationCompleteness"];
            cashFlow: components["schemas"]["CashFlowResult"];
            financing: null | components["schemas"]["FinancingResult"];
            energy: components["schemas"]["EnergyBreakdownResult"];
            otherRecurringCosts: components["schemas"]["RecurringCostResult"][];
            otherOneTimeCosts: components["schemas"]["OneTimeCostResult"][];
            netOwnershipCost: null | components["schemas"]["NetOwnershipCostResult"];
        };
        /** @enum {unknown} */
        MissingCategory: "vehicleTax" | "insurance" | "maintenanceAndRepairs" | "residualValue";
        NamedRecurringCostInput: {
            label: string;
            /** Format: double */
            amountSek: number;
            cadence: components["schemas"]["RecurringCostCadence"];
        };
        NetOwnershipCostResult: {
            /** Format: double */
            residualValueSek: number;
            /** Format: double */
            depreciationSek: number;
            /** Format: double */
            interestPaidSek: number;
            /** Format: double */
            knownOperatingCostSek: number;
            /** Format: double */
            knownTotalSek: number;
            /** Format: double */
            averagePerMonthSek: number;
            /** Format: double */
            averagePerYearSek: number;
            /** Format: double */
            estimatedEquityAtPeriodEndSek: number;
            isComplete: boolean;
        };
        OneTimeCostInput: {
            label: string;
            /** Format: double */
            amountSek: number;
        };
        OneTimeCostResult: {
            label: string;
            /** Format: double */
            amountSek: number;
        };
        /** @enum {unknown} */
        RecurringCostCadence: "monthly" | "annual";
        RecurringCostInput: {
            /** Format: double */
            amountSek: number;
            cadence: components["schemas"]["RecurringCostCadence"];
        };
        RecurringCostResult: {
            label: string;
            /** Format: double */
            amountSek: number;
            cadence: components["schemas"]["RecurringCostCadence"];
            /** Format: double */
            costDuringPeriodSek: number;
        };
        ReplaceSavedCostScenarioRequest: {
            /** Format: int64 */
            expectedRevision: number;
            scenario: components["schemas"]["ManualCalculationRequest"];
        };
        ReplaceSavedListingRequest: {
            /** Format: int64 */
            expectedRevision: number;
            listing: components["schemas"]["ReviewedListingInput"];
        };
        ReviewedListingInput: {
            submittedUrl: string;
            /** Format: date-time */
            analyzedAtUtc: string;
            requestedModel: null | string;
            /** Format: int32 */
            promptVersion: null | number;
            /** Format: int32 */
            schemaVersion: null | number;
            sources: string[];
            draft: components["schemas"]["ListingDraftInput"];
        };
        SavedCostScenarioProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            code: string;
            /** Format: uuid */
            existingVehicleId?: null | string;
            /** Format: int64 */
            expectedRevision?: null | number;
            /** Format: int64 */
            actualRevision?: null | number;
            /** Format: int32 */
            calculationVersion?: null | number;
            /** Format: int32 */
            resultSchemaVersion?: null | number;
        };
        SavedCostScenarioResponse: {
            /** Format: uuid */
            vehicleId: string;
            registrationNumber: string;
            /** Format: int64 */
            revision: number;
            /** Format: int32 */
            calculationVersion: number;
            /** Format: int32 */
            resultSchemaVersion: number;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
            /** Format: date-time */
            calculatedAtUtc: string;
            scenario: components["schemas"]["ManualCalculationRequest"];
            result: components["schemas"]["ManualCalculationResult"];
        };
        SavedCostScenarioSummaryResponse: {
            /** Format: uuid */
            vehicleId: string;
            registrationNumber: string;
            vehicleLabel: null | string;
            /** Format: int64 */
            revision: number;
            /** Format: double */
            purchasePriceSek: number;
            /** Format: int32 */
            calculationPeriodMonths: number;
            /** Format: double */
            cashFlowKnownTotalSek: number;
            /** Format: double */
            netOwnershipCostKnownTotalSek: null | number;
            completeness: components["schemas"]["CalculationCompleteness"];
            /** Format: date-time */
            updatedAtUtc: string;
        };
        SavedListingProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            code: string;
            /** Format: uuid */
            existingVehicleId?: null | string;
            /** Format: int64 */
            expectedRevision?: null | number;
            /** Format: int64 */
            actualRevision?: null | number;
            /** Format: int32 */
            listingSchemaVersion?: null | number;
            /** Format: int32 */
            promptVersion?: null | number;
            /** Format: int32 */
            schemaVersion?: null | number;
        };
        SavedListingResponse: {
            /** Format: uuid */
            vehicleId: string;
            registrationNumber: string;
            /** Format: int64 */
            revision: number;
            /** Format: int64 */
            listingVersion: number;
            /** Format: int32 */
            listingSchemaVersion: number;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
            /** Format: date-time */
            analyzedAtUtc: string;
            submittedUrl: string;
            normalizedUrl: string;
            status: components["schemas"]["ListingAnalysisStatus"];
            requestedModel: null | string;
            /** Format: int32 */
            promptVersion: null | number;
            /** Format: int32 */
            schemaVersion: null | number;
            sources: components["schemas"]["ListingAnalysisSourceResponse"][];
            listing: components["schemas"]["ListingDraftResponse"];
            missingFields: components["schemas"]["ListingFieldCode"][];
            hasSavedCostScenario: boolean;
        };
        SavedListingSummaryResponse: {
            /** Format: uuid */
            vehicleId: string;
            registrationNumber: string;
            vehicleLabel: null | string;
            /** Format: int64 */
            revision: number;
            /** Format: int64 */
            listingVersion: number;
            /** Format: int32 */
            listingSchemaVersion: number;
            make: null | string;
            model: null | string;
            /** Format: int32 */
            modelYear: null | number;
            /** Format: double */
            priceSek: null | number;
            /** Format: double */
            odometerKilometres: null | number;
            status: components["schemas"]["ListingAnalysisStatus"];
            /** Format: int32 */
            missingFieldCount: number;
            hasSavedCostScenario: boolean;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        /** @enum {unknown} */
        SellerType: "private" | "dealer";
        SourcedCollectionInputOfEnergyConsumptionInput: {
            values: components["schemas"]["EnergyConsumptionInput"][];
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedCollectionInputOfFuelType: {
            values: components["schemas"]["FuelType"][];
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedCollectionInputOfstring: {
            values: string[];
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedCollectionResponseOfEnergyConsumptionResponse: {
            values: components["schemas"]["EnergyConsumptionResponse"][];
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedCollectionResponseOfFuelType: {
            values: components["schemas"]["FuelType"][];
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedCollectionResponseOfstring: {
            values: string[];
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueInputOfBodyType: {
            value: components["schemas"]["BodyType"];
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueInputOfboolean: {
            value: boolean;
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueInputOfDateOnly: {
            /** Format: date */
            value: string;
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueInputOfdecimal: {
            /** Format: double */
            value: number;
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueInputOfDrivetrain: {
            value: components["schemas"]["Drivetrain"];
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueInputOfint: {
            /** Format: int32 */
            value: number;
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueInputOfSellerType: {
            value: components["schemas"]["SellerType"];
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueInputOfstring: {
            value: string;
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueInputOfTransmission: {
            value: components["schemas"]["Transmission"];
            provenance: components["schemas"]["FieldProvenanceInput"];
        };
        SourcedValueResponseOfBodyType: {
            value: components["schemas"]["BodyType"];
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueResponseOfboolean: {
            value: boolean;
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueResponseOfDateOnly: {
            /** Format: date */
            value: string;
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueResponseOfdecimal: {
            /** Format: double */
            value: number;
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueResponseOfDrivetrain: {
            value: components["schemas"]["Drivetrain"];
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueResponseOfint: {
            /** Format: int32 */
            value: number;
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueResponseOfSellerType: {
            value: components["schemas"]["SellerType"];
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueResponseOfstring: {
            value: string;
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SourcedValueResponseOfTransmission: {
            value: components["schemas"]["Transmission"];
            provenance: components["schemas"]["FieldProvenanceResponse"];
        };
        SystemStatusResponse: {
            status: string;
            version: string;
            database: string;
            features: components["schemas"]["FeatureStatusResponse"];
            integrations: components["schemas"]["IntegrationStatusResponse"];
        };
        /** @enum {unknown} */
        Transmission: "manual" | "automatic";
        ValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** @enum {unknown} */
        VerificationStatus: "unverified" | "userConfirmed" | "registryVerified";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
