// <auto-generated />
using System;
using CarExpenseCalculator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarExpenseCalculator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarExpenseDbContext))]
    [Migration("20260830181537_InitialSavedCostScenarios")]
    partial class InitialSavedCostScenarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnnualDistanceKilometres")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_distance_kilometres");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at_utc");

                    b.Property<int>("CalculationPeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_period_months");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_version");

                    b.Property<decimal?>("ExpectedResidualValueSek")
                        .HasColumnType("numeric")
                        .HasColumnName("expected_residual_value_sek");

                    b.Property<decimal?>("FinancingAnnualNominalInterestRatePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("financing_annual_nominal_interest_rate_percent");

                    b.Property<decimal?>("FinancingDownPaymentSek")
                        .HasColumnType("numeric")
                        .HasColumnName("financing_down_payment_sek");

                    b.Property<int?>("FinancingTermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("financing_term_months");

                    b.Property<decimal?>("InsuranceAmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("insurance_amount_sek");

                    b.Property<string>("InsuranceCadence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("insurance_cadence");

                    b.Property<decimal?>("MaintenanceAndRepairsAmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("maintenance_and_repairs_amount_sek");

                    b.Property<string>("MaintenanceAndRepairsCadence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("maintenance_and_repairs_cadence");

                    b.Property<decimal>("PurchasePriceSek")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase_price_sek");

                    b.Property<int>("ResultSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("result_schema_version");

                    b.Property<string>("ResultSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_snapshot");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<decimal?>("VehicleTaxAmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("vehicle_tax_amount_sek");

                    b.Property<string>("VehicleTaxCadence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("vehicle_tax_cadence");

                    b.HasKey("Id")
                        .HasName("pk_saved_cost_scenarios");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ux_saved_cost_scenarios_vehicle_id");

                    b.ToTable("saved_cost_scenarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_saved_cost_scenarios_annual_distance", "annual_distance_kilometres BETWEEN 0 AND 1000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_financing_presence", "(financing_down_payment_sek IS NULL AND financing_annual_nominal_interest_rate_percent IS NULL AND financing_term_months IS NULL) OR (financing_down_payment_sek IS NOT NULL AND financing_annual_nominal_interest_rate_percent IS NOT NULL AND financing_term_months IS NOT NULL)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_financing_values", "financing_down_payment_sek IS NULL OR (purchase_price_sek > 0 AND financing_down_payment_sek >= 0 AND financing_down_payment_sek < purchase_price_sek AND financing_annual_nominal_interest_rate_percent BETWEEN 0 AND 100 AND financing_term_months BETWEEN 1 AND 120)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_insurance_amount", "insurance_amount_sek IS NULL OR insurance_amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_insurance_presence", "(insurance_amount_sek IS NULL) = (insurance_cadence IS NULL)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_maintenance_amount", "maintenance_and_repairs_amount_sek IS NULL OR maintenance_and_repairs_amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_maintenance_presence", "(maintenance_and_repairs_amount_sek IS NULL) = (maintenance_and_repairs_cadence IS NULL)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_period", "calculation_period_months BETWEEN 1 AND 120");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_purchase_price", "purchase_price_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_recurring_cadences", "(vehicle_tax_cadence IS NULL OR vehicle_tax_cadence IN ('Monthly', 'Annual')) AND (insurance_cadence IS NULL OR insurance_cadence IN ('Monthly', 'Annual')) AND (maintenance_and_repairs_cadence IS NULL OR maintenance_and_repairs_cadence IN ('Monthly', 'Annual'))");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_residual_value", "expected_residual_value_sek IS NULL OR (expected_residual_value_sek BETWEEN 0 AND purchase_price_sek)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_vehicle_tax_amount", "vehicle_tax_amount_sek IS NULL OR vehicle_tax_amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_vehicle_tax_presence", "(vehicle_tax_amount_sek IS NULL) = (vehicle_tax_cadence IS NULL)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_versions", "calculation_version >= 1 AND result_schema_version >= 1");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioEnergySourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ConsumptionPer100Kilometres")
                        .HasColumnType("numeric")
                        .HasColumnName("consumption_per_100_kilometres");

                    b.Property<decimal>("DistanceSharePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("distance_share_percent");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal>("PricePerUnitSek")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_unit_sek");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_scenario_energy_sources");

                    b.HasIndex("ScenarioId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_scenario_energy_sources_scenario_id_position");

                    b.ToTable("scenario_energy_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_scenario_energy_sources_consumption", "consumption_per_100_kilometres > 0 AND consumption_per_100_kilometres <= 10000");

                            t.HasCheckConstraint("ck_scenario_energy_sources_position", "position BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_scenario_energy_sources_price", "price_per_unit_sek BETWEEN 0 AND 100000");

                            t.HasCheckConstraint("ck_scenario_energy_sources_share", "distance_share_percent > 0 AND distance_share_percent <= 100");

                            t.HasCheckConstraint("ck_scenario_energy_sources_unit", "unit IN ('Litre', 'KilowattHour', 'Kilogram')");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioOneTimeCostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_sek");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.HasKey("Id")
                        .HasName("pk_scenario_one_time_costs");

                    b.HasIndex("ScenarioId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_scenario_one_time_costs_scenario_id_position");

                    b.ToTable("scenario_one_time_costs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scenario_one_time_costs_amount", "amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_scenario_one_time_costs_position", "position BETWEEN 0 AND 49");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioRecurringCostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_sek");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cadence");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.HasKey("Id")
                        .HasName("pk_scenario_recurring_costs");

                    b.HasIndex("ScenarioId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_scenario_recurring_costs_scenario_id_position");

                    b.ToTable("scenario_recurring_costs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scenario_recurring_costs_amount", "amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_scenario_recurring_costs_cadence", "cadence IN ('Monthly', 'Annual')");

                            t.HasCheckConstraint("ck_scenario_recurring_costs_position", "position BETWEEN 0 AND 49");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("registration_number");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VehicleLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("vehicle_label");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_registration_number");

                    b.HasIndex("UpdatedAtUtc", "Id")
                        .HasDatabaseName("ix_vehicles_updated_at_utc_id");

                    b.ToTable("vehicles", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_registration_number", "registration_number ~ '^[A-HJ-PR-UW-Z]{3}[0-9]{2}([0-9]|[A-HJ-NPR-UW-Z])$'");

                            t.HasCheckConstraint("ck_vehicles_revision", "revision >= 1");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.VehicleEntity", "Vehicle")
                        .WithOne("Scenario")
                        .HasForeignKey("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_cost_scenarios_vehicles");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioEnergySourceEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", "Scenario")
                        .WithMany("EnergySources")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_energy_sources_scenarios");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioOneTimeCostEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", "Scenario")
                        .WithMany("OtherOneTimeCosts")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_one_time_costs_scenarios");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioRecurringCostEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", "Scenario")
                        .WithMany("OtherRecurringCosts")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_recurring_costs_scenarios");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", b =>
                {
                    b.Navigation("EnergySources");

                    b.Navigation("OtherOneTimeCosts");

                    b.Navigation("OtherRecurringCosts");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.VehicleEntity", b =>
                {
                    b.Navigation("Scenario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
