// <auto-generated />
using System;
using CarExpenseCalculator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarExpenseCalculator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarExpenseDbContext))]
    [Migration("20260904100409_AddCurrentVehicleListings")]
    partial class AddCurrentVehicleListings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnnualDistanceKilometres")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_distance_kilometres");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at_utc");

                    b.Property<int>("CalculationPeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_period_months");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_version");

                    b.Property<decimal?>("ExpectedResidualValueSek")
                        .HasColumnType("numeric")
                        .HasColumnName("expected_residual_value_sek");

                    b.Property<decimal?>("FinancingAnnualNominalInterestRatePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("financing_annual_nominal_interest_rate_percent");

                    b.Property<decimal?>("FinancingDownPaymentSek")
                        .HasColumnType("numeric")
                        .HasColumnName("financing_down_payment_sek");

                    b.Property<int?>("FinancingTermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("financing_term_months");

                    b.Property<decimal?>("InsuranceAmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("insurance_amount_sek");

                    b.Property<string>("InsuranceCadence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("insurance_cadence");

                    b.Property<decimal?>("MaintenanceAndRepairsAmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("maintenance_and_repairs_amount_sek");

                    b.Property<string>("MaintenanceAndRepairsCadence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("maintenance_and_repairs_cadence");

                    b.Property<decimal>("PurchasePriceSek")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase_price_sek");

                    b.Property<int>("ResultSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("result_schema_version");

                    b.Property<string>("ResultSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_snapshot");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<decimal?>("VehicleTaxAmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("vehicle_tax_amount_sek");

                    b.Property<string>("VehicleTaxCadence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("vehicle_tax_cadence");

                    b.HasKey("Id")
                        .HasName("pk_saved_cost_scenarios");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ux_saved_cost_scenarios_vehicle_id");

                    b.ToTable("saved_cost_scenarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_saved_cost_scenarios_annual_distance", "annual_distance_kilometres BETWEEN 0 AND 1000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_financing_presence", "(financing_down_payment_sek IS NULL AND financing_annual_nominal_interest_rate_percent IS NULL AND financing_term_months IS NULL) OR (financing_down_payment_sek IS NOT NULL AND financing_annual_nominal_interest_rate_percent IS NOT NULL AND financing_term_months IS NOT NULL)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_financing_values", "financing_down_payment_sek IS NULL OR (purchase_price_sek > 0 AND financing_down_payment_sek >= 0 AND financing_down_payment_sek < purchase_price_sek AND financing_annual_nominal_interest_rate_percent BETWEEN 0 AND 100 AND financing_term_months BETWEEN 1 AND 120)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_insurance_amount", "insurance_amount_sek IS NULL OR insurance_amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_insurance_presence", "(insurance_amount_sek IS NULL) = (insurance_cadence IS NULL)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_maintenance_amount", "maintenance_and_repairs_amount_sek IS NULL OR maintenance_and_repairs_amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_maintenance_presence", "(maintenance_and_repairs_amount_sek IS NULL) = (maintenance_and_repairs_cadence IS NULL)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_period", "calculation_period_months BETWEEN 1 AND 120");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_purchase_price", "purchase_price_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_recurring_cadences", "(vehicle_tax_cadence IS NULL OR vehicle_tax_cadence IN ('Monthly', 'Annual')) AND (insurance_cadence IS NULL OR insurance_cadence IN ('Monthly', 'Annual')) AND (maintenance_and_repairs_cadence IS NULL OR maintenance_and_repairs_cadence IN ('Monthly', 'Annual'))");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_residual_value", "expected_residual_value_sek IS NULL OR (expected_residual_value_sek BETWEEN 0 AND purchase_price_sek)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_vehicle_tax_amount", "vehicle_tax_amount_sek IS NULL OR vehicle_tax_amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_vehicle_tax_presence", "(vehicle_tax_amount_sek IS NULL) = (vehicle_tax_cadence IS NULL)");

                            t.HasCheckConstraint("ck_saved_cost_scenarios_versions", "calculation_version >= 1 AND result_schema_version >= 1");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioEnergySourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ConsumptionPer100Kilometres")
                        .HasColumnType("numeric")
                        .HasColumnName("consumption_per_100_kilometres");

                    b.Property<decimal>("DistanceSharePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("distance_share_percent");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal>("PricePerUnitSek")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_unit_sek");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_scenario_energy_sources");

                    b.HasIndex("ScenarioId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_scenario_energy_sources_scenario_id_position");

                    b.ToTable("scenario_energy_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_scenario_energy_sources_consumption", "consumption_per_100_kilometres > 0 AND consumption_per_100_kilometres <= 10000");

                            t.HasCheckConstraint("ck_scenario_energy_sources_position", "position BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_scenario_energy_sources_price", "price_per_unit_sek BETWEEN 0 AND 100000");

                            t.HasCheckConstraint("ck_scenario_energy_sources_share", "distance_share_percent > 0 AND distance_share_percent <= 100");

                            t.HasCheckConstraint("ck_scenario_energy_sources_unit", "unit IN ('Litre', 'KilowattHour', 'Kilogram')");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioOneTimeCostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_sek");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.HasKey("Id")
                        .HasName("pk_scenario_one_time_costs");

                    b.HasIndex("ScenarioId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_scenario_one_time_costs_scenario_id_position");

                    b.ToTable("scenario_one_time_costs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scenario_one_time_costs_amount", "amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_scenario_one_time_costs_position", "position BETWEEN 0 AND 49");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioRecurringCostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountSek")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_sek");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cadence");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.HasKey("Id")
                        .HasName("pk_scenario_recurring_costs");

                    b.HasIndex("ScenarioId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_scenario_recurring_costs_scenario_id_position");

                    b.ToTable("scenario_recurring_costs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scenario_recurring_costs_amount", "amount_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_scenario_recurring_costs_cadence", "cadence IN ('Monthly', 'Annual')");

                            t.HasCheckConstraint("ck_scenario_recurring_costs_position", "position BETWEEN 0 AND 49");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.ListingEquipmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_listing_equipment");

                    b.HasIndex("ListingId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_listing_equipment_listing_id_position");

                    b.ToTable("listing_equipment", null, t =>
                        {
                            t.HasCheckConstraint("ck_listing_equipment_position", "position BETWEEN 0 AND 99");

                            t.HasCheckConstraint("ck_listing_equipment_value", "length(btrim(value)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.ListingSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<bool>("MatchesSubmittedUrl")
                        .HasColumnType("boolean")
                        .HasColumnName("matches_submitted_url");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_listing_sources");

                    b.HasIndex("ListingId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_listing_sources_listing_id_position");

                    b.ToTable("listing_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_listing_sources_position", "position >= 0");

                            t.HasCheckConstraint("ck_listing_sources_url", "length(btrim(url)) BETWEEN 1 AND 2048");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.VehicleListingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AdvertisedUpdatedDate")
                        .HasColumnType("date")
                        .HasColumnName("advertised_updated_date");

                    b.Property<DateTimeOffset>("AnalyzedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at_utc");

                    b.Property<decimal?>("AnnualVehicleTaxSek")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_vehicle_tax_sek");

                    b.Property<string>("BodyType")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("body_type");

                    b.Property<string>("Colour")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colour");

                    b.Property<string>("ConditionNotesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("condition_notes");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("county");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Drivetrain")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("drivetrain");

                    b.Property<string>("EnergyConsumptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("energy_consumptions");

                    b.Property<decimal?>("EngineDisplacementCubicCentimetres")
                        .HasColumnType("numeric")
                        .HasColumnName("engine_displacement_cubic_centimetres");

                    b.Property<bool>("EquipmentKnown")
                        .HasColumnType("boolean")
                        .HasColumnName("equipment_known");

                    b.Property<int?>("ExtractionSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("extraction_schema_version");

                    b.Property<string>("FieldProvenanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_provenance");

                    b.Property<DateOnly?>("FirstRegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("first_registration_date");

                    b.PrimitiveCollection<string[]>("FuelTypes")
                        .HasColumnType("text[]")
                        .HasColumnName("fuel_types");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("integer")
                        .HasColumnName("horsepower");

                    b.Property<int?>("ImageCount")
                        .HasColumnType("integer")
                        .HasColumnName("image_count");

                    b.Property<DateOnly?>("LastInspectionDate")
                        .HasColumnType("date")
                        .HasColumnName("last_inspection_date");

                    b.Property<int>("ListingSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("listing_schema_version");

                    b.Property<long>("ListingVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("listing_version");

                    b.Property<string>("Locality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.PrimitiveCollection<string[]>("MissingFields")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("missing_fields");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("integer")
                        .HasColumnName("model_year");

                    b.Property<DateOnly?>("NextInspectionDate")
                        .HasColumnType("date")
                        .HasColumnName("next_inspection_date");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_url");

                    b.Property<decimal?>("OdometerKilometres")
                        .HasColumnType("numeric")
                        .HasColumnName("odometer_kilometres");

                    b.Property<int?>("OwnerCount")
                        .HasColumnType("integer")
                        .HasColumnName("owner_count");

                    b.Property<decimal?>("PriceSek")
                        .HasColumnType("numeric")
                        .HasColumnName("price_sek");

                    b.Property<int?>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date")
                        .HasColumnName("published_date");

                    b.Property<string>("RequestedModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_model");

                    b.Property<string>("SellerClaimsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("seller_claims");

                    b.Property<string>("SellerType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("seller_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("submitted_url");

                    b.Property<bool?>("TowBar")
                        .HasColumnType("boolean")
                        .HasColumnName("tow_bar");

                    b.Property<string>("Transmission")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("transmission");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Variant")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variant");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vin");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_listings");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicle_listings_vehicle_id");

                    b.ToTable("vehicle_listings", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_listings_annual_tax", "annual_vehicle_tax_sek IS NULL OR annual_vehicle_tax_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_vehicle_listings_body_type", "body_type IS NULL OR body_type IN ('Sedan', 'Hatchback', 'Wagon', 'Suv', 'Coupe', 'Convertible', 'Minivan', 'Pickup', 'Van', 'Other')");

                            t.HasCheckConstraint("ck_vehicle_listings_condition_notes", "condition_notes IS NULL OR (jsonb_typeof(condition_notes) = 'array' AND jsonb_array_length(condition_notes) <= 10)");

                            t.HasCheckConstraint("ck_vehicle_listings_drivetrain", "drivetrain IS NULL OR drivetrain IN ('FrontWheelDrive', 'RearWheelDrive', 'AllWheelDrive')");

                            t.HasCheckConstraint("ck_vehicle_listings_energy_consumptions", "energy_consumptions IS NULL OR (jsonb_typeof(energy_consumptions) = 'array' AND jsonb_array_length(energy_consumptions) <= 2)");

                            t.HasCheckConstraint("ck_vehicle_listings_engine_displacement", "engine_displacement_cubic_centimetres IS NULL OR (engine_displacement_cubic_centimetres > 0 AND engine_displacement_cubic_centimetres <= 100000)");

                            t.HasCheckConstraint("ck_vehicle_listings_extraction_metadata", "(requested_model IS NULL AND prompt_version IS NULL AND extraction_schema_version IS NULL) OR (requested_model IS NOT NULL AND length(btrim(requested_model)) BETWEEN 1 AND 100 AND prompt_version IS NOT NULL AND prompt_version = 2 AND extraction_schema_version IS NOT NULL AND extraction_schema_version = 2)");

                            t.HasCheckConstraint("ck_vehicle_listings_field_provenance", "jsonb_typeof(field_provenance) = 'object'");

                            t.HasCheckConstraint("ck_vehicle_listings_fuel_types", "fuel_types IS NULL OR (cardinality(fuel_types) <= 9 AND fuel_types <@ ARRAY['Petrol','Diesel','Electricity','Ethanol','Biogas','NaturalGas','LiquefiedPetroleumGas','Hydrogen','Other']::text[])");

                            t.HasCheckConstraint("ck_vehicle_listings_horsepower", "horsepower IS NULL OR horsepower BETWEEN 1 AND 10000");

                            t.HasCheckConstraint("ck_vehicle_listings_image_count", "image_count IS NULL OR image_count BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_vehicle_listings_missing_fields", "cardinality(missing_fields) <= 31 AND missing_fields <@ ARRAY['RegistrationNumber','Make','Model','Variant','ModelYear','Vin','PriceSek','OdometerKilometres','SellerType','Locality','County','PublishedDate','UpdatedDate','ImageCount','FuelTypes','Transmission','Drivetrain','BodyType','Colour','Horsepower','EngineDisplacementCubicCentimetres','EnergyConsumptions','AnnualVehicleTaxSek','OwnerCount','FirstRegistrationDate','LastInspectionDate','NextInspectionDate','TowBar','Equipment','SellerClaims','ConditionNotes']::text[]");

                            t.HasCheckConstraint("ck_vehicle_listings_model_year", "model_year IS NULL OR model_year BETWEEN 1886 AND 2100");

                            t.HasCheckConstraint("ck_vehicle_listings_odometer", "odometer_kilometres IS NULL OR odometer_kilometres BETWEEN 0 AND 10000000");

                            t.HasCheckConstraint("ck_vehicle_listings_owner_count", "owner_count IS NULL OR owner_count BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_vehicle_listings_price", "price_sek IS NULL OR price_sek BETWEEN 0 AND 100000000");

                            t.HasCheckConstraint("ck_vehicle_listings_seller_claims", "seller_claims IS NULL OR (jsonb_typeof(seller_claims) = 'array' AND jsonb_array_length(seller_claims) <= 20)");

                            t.HasCheckConstraint("ck_vehicle_listings_seller_type", "seller_type IS NULL OR seller_type IN ('Private', 'Dealer')");

                            t.HasCheckConstraint("ck_vehicle_listings_status", "status IN ('Complete', 'Partial', 'Unavailable')");

                            t.HasCheckConstraint("ck_vehicle_listings_transmission", "transmission IS NULL OR transmission IN ('Manual', 'Automatic')");

                            t.HasCheckConstraint("ck_vehicle_listings_urls", "length(submitted_url) BETWEEN 1 AND 2048 AND length(normalized_url) BETWEEN 1 AND 2048");

                            t.HasCheckConstraint("ck_vehicle_listings_versions", "listing_version >= 1 AND listing_schema_version = 1");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.Vehicles.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("registration_number");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VehicleLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("vehicle_label");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_registration_number");

                    b.HasIndex("UpdatedAtUtc", "Id")
                        .HasDatabaseName("ix_vehicles_updated_at_utc_id");

                    b.ToTable("vehicles", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_registration_number", "registration_number ~ '^[A-HJ-PR-UW-Z]{3}[0-9]{2}([0-9]|[A-HJ-NPR-UW-Z])$'");

                            t.HasCheckConstraint("ck_vehicles_revision", "revision >= 1");
                        });
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.Vehicles.VehicleEntity", "Vehicle")
                        .WithOne("Scenario")
                        .HasForeignKey("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_cost_scenarios_vehicles");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioEnergySourceEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", "Scenario")
                        .WithMany("EnergySources")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_energy_sources_scenarios");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioOneTimeCostEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", "Scenario")
                        .WithMany("OtherOneTimeCosts")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_one_time_costs_scenarios");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.ScenarioRecurringCostEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", "Scenario")
                        .WithMany("OtherRecurringCosts")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_recurring_costs_scenarios");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.ListingEquipmentEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.VehicleListingEntity", "Listing")
                        .WithMany("Equipment")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_equipment_vehicle_listings");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.ListingSourceEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.VehicleListingEntity", "Listing")
                        .WithMany("Sources")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_sources_vehicle_listings");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.VehicleListingEntity", b =>
                {
                    b.HasOne("CarExpenseCalculator.Infrastructure.Persistence.Vehicles.VehicleEntity", "Vehicle")
                        .WithOne("Listing")
                        .HasForeignKey("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.VehicleListingEntity", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_listings_vehicles");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedCostScenarios.SavedCostScenarioEntity", b =>
                {
                    b.Navigation("EnergySources");

                    b.Navigation("OtherOneTimeCosts");

                    b.Navigation("OtherRecurringCosts");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.SavedListings.VehicleListingEntity", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("CarExpenseCalculator.Infrastructure.Persistence.Vehicles.VehicleEntity", b =>
                {
                    b.Navigation("Listing");

                    b.Navigation("Scenario");
                });
#pragma warning restore 612, 618
        }
    }
}
